# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cidade.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'cidade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63idade.proto\x12\x06\x63idade\"<\n\x10\x44iscoveryRequest\x12\x12\n\ngateway_ip\x18\x01 \x01(\t\x12\x14\n\x0cgateway_port\x18\x02 \x01(\x05\"x\n\x11\x44iscoveryResponse\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x10\n\x08udp_port\x18\x04 \x01(\x05\x12\x14\n\x0c\x63ontrollable\x18\x05 \x01(\x08\x12\x0e\n\x06status\x18\x06 \x01(\t\"\xc7\x01\n\x07Leitura\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x15\n\x0btemperatura\x18\x04 \x01(\x02H\x00\x12\x11\n\x07umidade\x18\x05 \x01(\x02H\x00\x12\r\n\x03\x63o2\x18\x06 \x01(\x02H\x00\x12\x0f\n\x05ruido\x18\x07 \x01(\x02H\x00\x12\x12\n\x08\x63ontagem\x18\x08 \x01(\x05H\x00\x12\x11\n\x07\x65nergia\x18\t \x01(\x02H\x00\x12\x0e\n\x06\x61lerta\x18\n \x01(\x08\x42\x07\n\x05valor\"9\n\x07\x43omando\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x63\x61o\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x02\"4\n\x0fRespostaComando\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"U\n\x11RequisicaoCliente\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12 \n\x07\x63omando\x18\x02 \x01(\x0b\x32\x0f.cidade.Comando\x12\x10\n\x08\x63onsulta\x18\x03 \x01(\t\"\x92\x01\n\x0fRespostaGateway\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12)\n\x06\x66ontes\x18\x02 \x03(\x0b\x32\x19.cidade.DiscoveryResponse\x12.\n\rresultado_cmd\x18\x03 \x01(\x0b\x32\x17.cidade.RespostaComando\x12\x16\n\x0e\x64\x61\x64os_consulta\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cidade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISCOVERYREQUEST']._serialized_start=24
  _globals['_DISCOVERYREQUEST']._serialized_end=84
  _globals['_DISCOVERYRESPONSE']._serialized_start=86
  _globals['_DISCOVERYRESPONSE']._serialized_end=206
  _globals['_LEITURA']._serialized_start=209
  _globals['_LEITURA']._serialized_end=408
  _globals['_COMANDO']._serialized_start=410
  _globals['_COMANDO']._serialized_end=467
  _globals['_RESPOSTACOMANDO']._serialized_start=469
  _globals['_RESPOSTACOMANDO']._serialized_end=521
  _globals['_REQUISICAOCLIENTE']._serialized_start=523
  _globals['_REQUISICAOCLIENTE']._serialized_end=608
  _globals['_RESPOSTAGATEWAY']._serialized_start=611
  _globals['_RESPOSTAGATEWAY']._serialized_end=757
# @@protoc_insertion_point(module_scope)
