/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cidade.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cidade.pb-c.h"
void   cidade__discovery_request__init
                     (Cidade__DiscoveryRequest         *message)
{
  static const Cidade__DiscoveryRequest init_value = CIDADE__DISCOVERY_REQUEST__INIT;
  *message = init_value;
}
size_t cidade__discovery_request__get_packed_size
                     (const Cidade__DiscoveryRequest *message)
{
  assert(message->base.descriptor == &cidade__discovery_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__discovery_request__pack
                     (const Cidade__DiscoveryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__discovery_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__discovery_request__pack_to_buffer
                     (const Cidade__DiscoveryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__discovery_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__DiscoveryRequest *
       cidade__discovery_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__DiscoveryRequest *)
     protobuf_c_message_unpack (&cidade__discovery_request__descriptor,
                                allocator, len, data);
}
void   cidade__discovery_request__free_unpacked
                     (Cidade__DiscoveryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__discovery_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cidade__discovery_response__init
                     (Cidade__DiscoveryResponse         *message)
{
  static const Cidade__DiscoveryResponse init_value = CIDADE__DISCOVERY_RESPONSE__INIT;
  *message = init_value;
}
size_t cidade__discovery_response__get_packed_size
                     (const Cidade__DiscoveryResponse *message)
{
  assert(message->base.descriptor == &cidade__discovery_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__discovery_response__pack
                     (const Cidade__DiscoveryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__discovery_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__discovery_response__pack_to_buffer
                     (const Cidade__DiscoveryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__discovery_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__DiscoveryResponse *
       cidade__discovery_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__DiscoveryResponse *)
     protobuf_c_message_unpack (&cidade__discovery_response__descriptor,
                                allocator, len, data);
}
void   cidade__discovery_response__free_unpacked
                     (Cidade__DiscoveryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__discovery_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cidade__leitura__init
                     (Cidade__Leitura         *message)
{
  static const Cidade__Leitura init_value = CIDADE__LEITURA__INIT;
  *message = init_value;
}
size_t cidade__leitura__get_packed_size
                     (const Cidade__Leitura *message)
{
  assert(message->base.descriptor == &cidade__leitura__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__leitura__pack
                     (const Cidade__Leitura *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__leitura__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__leitura__pack_to_buffer
                     (const Cidade__Leitura *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__leitura__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__Leitura *
       cidade__leitura__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__Leitura *)
     protobuf_c_message_unpack (&cidade__leitura__descriptor,
                                allocator, len, data);
}
void   cidade__leitura__free_unpacked
                     (Cidade__Leitura *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__leitura__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cidade__comando__init
                     (Cidade__Comando         *message)
{
  static const Cidade__Comando init_value = CIDADE__COMANDO__INIT;
  *message = init_value;
}
size_t cidade__comando__get_packed_size
                     (const Cidade__Comando *message)
{
  assert(message->base.descriptor == &cidade__comando__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__comando__pack
                     (const Cidade__Comando *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__comando__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__comando__pack_to_buffer
                     (const Cidade__Comando *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__comando__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__Comando *
       cidade__comando__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__Comando *)
     protobuf_c_message_unpack (&cidade__comando__descriptor,
                                allocator, len, data);
}
void   cidade__comando__free_unpacked
                     (Cidade__Comando *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__comando__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cidade__resposta_comando__init
                     (Cidade__RespostaComando         *message)
{
  static const Cidade__RespostaComando init_value = CIDADE__RESPOSTA_COMANDO__INIT;
  *message = init_value;
}
size_t cidade__resposta_comando__get_packed_size
                     (const Cidade__RespostaComando *message)
{
  assert(message->base.descriptor == &cidade__resposta_comando__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__resposta_comando__pack
                     (const Cidade__RespostaComando *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__resposta_comando__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__resposta_comando__pack_to_buffer
                     (const Cidade__RespostaComando *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__resposta_comando__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__RespostaComando *
       cidade__resposta_comando__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__RespostaComando *)
     protobuf_c_message_unpack (&cidade__resposta_comando__descriptor,
                                allocator, len, data);
}
void   cidade__resposta_comando__free_unpacked
                     (Cidade__RespostaComando *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__resposta_comando__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cidade__requisicao_cliente__init
                     (Cidade__RequisicaoCliente         *message)
{
  static const Cidade__RequisicaoCliente init_value = CIDADE__REQUISICAO_CLIENTE__INIT;
  *message = init_value;
}
size_t cidade__requisicao_cliente__get_packed_size
                     (const Cidade__RequisicaoCliente *message)
{
  assert(message->base.descriptor == &cidade__requisicao_cliente__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__requisicao_cliente__pack
                     (const Cidade__RequisicaoCliente *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__requisicao_cliente__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__requisicao_cliente__pack_to_buffer
                     (const Cidade__RequisicaoCliente *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__requisicao_cliente__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__RequisicaoCliente *
       cidade__requisicao_cliente__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__RequisicaoCliente *)
     protobuf_c_message_unpack (&cidade__requisicao_cliente__descriptor,
                                allocator, len, data);
}
void   cidade__requisicao_cliente__free_unpacked
                     (Cidade__RequisicaoCliente *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__requisicao_cliente__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cidade__resposta_gateway__init
                     (Cidade__RespostaGateway         *message)
{
  static const Cidade__RespostaGateway init_value = CIDADE__RESPOSTA_GATEWAY__INIT;
  *message = init_value;
}
size_t cidade__resposta_gateway__get_packed_size
                     (const Cidade__RespostaGateway *message)
{
  assert(message->base.descriptor == &cidade__resposta_gateway__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cidade__resposta_gateway__pack
                     (const Cidade__RespostaGateway *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cidade__resposta_gateway__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cidade__resposta_gateway__pack_to_buffer
                     (const Cidade__RespostaGateway *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cidade__resposta_gateway__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cidade__RespostaGateway *
       cidade__resposta_gateway__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cidade__RespostaGateway *)
     protobuf_c_message_unpack (&cidade__resposta_gateway__descriptor,
                                allocator, len, data);
}
void   cidade__resposta_gateway__free_unpacked
                     (Cidade__RespostaGateway *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cidade__resposta_gateway__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cidade__discovery_request__field_descriptors[2] =
{
  {
    "gateway_ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryRequest, gateway_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryRequest, gateway_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__discovery_request__field_indices_by_name[] = {
  0,   /* field[0] = gateway_ip */
  1,   /* field[1] = gateway_port */
};
static const ProtobufCIntRange cidade__discovery_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cidade__discovery_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.DiscoveryRequest",
  "DiscoveryRequest",
  "Cidade__DiscoveryRequest",
  "cidade",
  sizeof(Cidade__DiscoveryRequest),
  2,
  cidade__discovery_request__field_descriptors,
  cidade__discovery_request__field_indices_by_name,
  1,  cidade__discovery_request__number_ranges,
  (ProtobufCMessageInit) cidade__discovery_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cidade__discovery_response__field_descriptors[6] =
{
  {
    "source_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryResponse, source_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryResponse, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryResponse, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "udp_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryResponse, udp_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "controllable",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryResponse, controllable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__DiscoveryResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__discovery_response__field_indices_by_name[] = {
  4,   /* field[4] = controllable */
  2,   /* field[2] = ip */
  0,   /* field[0] = source_id */
  5,   /* field[5] = status */
  1,   /* field[1] = type */
  3,   /* field[3] = udp_port */
};
static const ProtobufCIntRange cidade__discovery_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor cidade__discovery_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.DiscoveryResponse",
  "DiscoveryResponse",
  "Cidade__DiscoveryResponse",
  "cidade",
  sizeof(Cidade__DiscoveryResponse),
  6,
  cidade__discovery_response__field_descriptors,
  cidade__discovery_response__field_indices_by_name,
  1,  cidade__discovery_response__number_ranges,
  (ProtobufCMessageInit) cidade__discovery_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cidade__leitura__field_descriptors[10] =
{
  {
    "source_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__Leitura, source_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__Leitura, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Cidade__Leitura, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperatura",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Cidade__Leitura, valor_case),
    offsetof(Cidade__Leitura, temperatura),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "umidade",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Cidade__Leitura, valor_case),
    offsetof(Cidade__Leitura, umidade),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co2",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Cidade__Leitura, valor_case),
    offsetof(Cidade__Leitura, co2),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ruido",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Cidade__Leitura, valor_case),
    offsetof(Cidade__Leitura, ruido),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contagem",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Cidade__Leitura, valor_case),
    offsetof(Cidade__Leitura, contagem),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energia",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Cidade__Leitura, valor_case),
    offsetof(Cidade__Leitura, energia),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alerta",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cidade__Leitura, alerta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__leitura__field_indices_by_name[] = {
  9,   /* field[9] = alerta */
  5,   /* field[5] = co2 */
  7,   /* field[7] = contagem */
  8,   /* field[8] = energia */
  6,   /* field[6] = ruido */
  0,   /* field[0] = source_id */
  3,   /* field[3] = temperatura */
  2,   /* field[2] = timestamp */
  1,   /* field[1] = type */
  4,   /* field[4] = umidade */
};
static const ProtobufCIntRange cidade__leitura__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor cidade__leitura__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.Leitura",
  "Leitura",
  "Cidade__Leitura",
  "cidade",
  sizeof(Cidade__Leitura),
  10,
  cidade__leitura__field_descriptors,
  cidade__leitura__field_indices_by_name,
  1,  cidade__leitura__number_ranges,
  (ProtobufCMessageInit) cidade__leitura__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cidade__comando__field_descriptors[3] =
{
  {
    "source_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__Comando, source_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acao",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__Comando, acao),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valor",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Cidade__Comando, valor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__comando__field_indices_by_name[] = {
  1,   /* field[1] = acao */
  0,   /* field[0] = source_id */
  2,   /* field[2] = valor */
};
static const ProtobufCIntRange cidade__comando__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cidade__comando__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.Comando",
  "Comando",
  "Cidade__Comando",
  "cidade",
  sizeof(Cidade__Comando),
  3,
  cidade__comando__field_descriptors,
  cidade__comando__field_indices_by_name,
  1,  cidade__comando__number_ranges,
  (ProtobufCMessageInit) cidade__comando__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cidade__resposta_comando__field_descriptors[2] =
{
  {
    "sucesso",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cidade__RespostaComando, sucesso),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mensagem",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__RespostaComando, mensagem),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__resposta_comando__field_indices_by_name[] = {
  1,   /* field[1] = mensagem */
  0,   /* field[0] = sucesso */
};
static const ProtobufCIntRange cidade__resposta_comando__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cidade__resposta_comando__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.RespostaComando",
  "RespostaComando",
  "Cidade__RespostaComando",
  "cidade",
  sizeof(Cidade__RespostaComando),
  2,
  cidade__resposta_comando__field_descriptors,
  cidade__resposta_comando__field_indices_by_name,
  1,  cidade__resposta_comando__number_ranges,
  (ProtobufCMessageInit) cidade__resposta_comando__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cidade__requisicao_cliente__field_descriptors[3] =
{
  {
    "tipo",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__RequisicaoCliente, tipo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comando",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cidade__RequisicaoCliente, comando),
    &cidade__comando__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "consulta",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__RequisicaoCliente, consulta),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__requisicao_cliente__field_indices_by_name[] = {
  1,   /* field[1] = comando */
  2,   /* field[2] = consulta */
  0,   /* field[0] = tipo */
};
static const ProtobufCIntRange cidade__requisicao_cliente__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cidade__requisicao_cliente__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.RequisicaoCliente",
  "RequisicaoCliente",
  "Cidade__RequisicaoCliente",
  "cidade",
  sizeof(Cidade__RequisicaoCliente),
  3,
  cidade__requisicao_cliente__field_descriptors,
  cidade__requisicao_cliente__field_indices_by_name,
  1,  cidade__requisicao_cliente__number_ranges,
  (ProtobufCMessageInit) cidade__requisicao_cliente__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cidade__resposta_gateway__field_descriptors[4] =
{
  {
    "tipo",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__RespostaGateway, tipo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fontes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Cidade__RespostaGateway, n_fontes),
    offsetof(Cidade__RespostaGateway, fontes),
    &cidade__discovery_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resultado_cmd",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cidade__RespostaGateway, resultado_cmd),
    &cidade__resposta_comando__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dados_consulta",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cidade__RespostaGateway, dados_consulta),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cidade__resposta_gateway__field_indices_by_name[] = {
  3,   /* field[3] = dados_consulta */
  1,   /* field[1] = fontes */
  2,   /* field[2] = resultado_cmd */
  0,   /* field[0] = tipo */
};
static const ProtobufCIntRange cidade__resposta_gateway__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cidade__resposta_gateway__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cidade.RespostaGateway",
  "RespostaGateway",
  "Cidade__RespostaGateway",
  "cidade",
  sizeof(Cidade__RespostaGateway),
  4,
  cidade__resposta_gateway__field_descriptors,
  cidade__resposta_gateway__field_indices_by_name,
  1,  cidade__resposta_gateway__number_ranges,
  (ProtobufCMessageInit) cidade__resposta_gateway__init,
  NULL,NULL,NULL    /* reserved[123] */
};
