/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cidade.proto */

#ifndef PROTOBUF_C_cidade_2eproto__INCLUDED
#define PROTOBUF_C_cidade_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Cidade__DiscoveryRequest Cidade__DiscoveryRequest;
typedef struct Cidade__DiscoveryResponse Cidade__DiscoveryResponse;
typedef struct Cidade__Leitura Cidade__Leitura;
typedef struct Cidade__Comando Cidade__Comando;
typedef struct Cidade__RespostaComando Cidade__RespostaComando;
typedef struct Cidade__RequisicaoCliente Cidade__RequisicaoCliente;
typedef struct Cidade__RespostaGateway Cidade__RespostaGateway;


/* --- enums --- */


/* --- messages --- */

/*
 * Gateway envia isso no multicast pedindo que fontes se identifiquem
 */
struct  Cidade__DiscoveryRequest
{
  ProtobufCMessage base;
  char *gateway_ip;
  /*
   * porta TCP do gateway
   */
  int32_t gateway_port;
};
#define CIDADE__DISCOVERY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__discovery_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/*
 * Cada fonte responde com isso
 */
struct  Cidade__DiscoveryResponse
{
  ProtobufCMessage base;
  /*
   * ex: "sensor_temp_01"
   */
  char *source_id;
  /*
   * ex: "temperatura", "qualidade_ar", "trafego"
   */
  char *type;
  char *ip;
  /*
   * porta onde a fonte envia dados UDP
   */
  int32_t udp_port;
  /*
   * é controlável?
   */
  protobuf_c_boolean controllable;
  /*
   * "ativo", "inativo"
   */
  char *status;
};
#define CIDADE__DISCOVERY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__discovery_response__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


typedef enum {
  CIDADE__LEITURA__VALOR__NOT_SET = 0,
  CIDADE__LEITURA__VALOR_TEMPERATURA = 4,
  CIDADE__LEITURA__VALOR_UMIDADE = 5,
  CIDADE__LEITURA__VALOR_CO2 = 6,
  CIDADE__LEITURA__VALOR_RUIDO = 7,
  CIDADE__LEITURA__VALOR_CONTAGEM = 8,
  CIDADE__LEITURA__VALOR_ENERGIA = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CIDADE__LEITURA__VALOR__CASE)
} Cidade__Leitura__ValorCase;

struct  Cidade__Leitura
{
  ProtobufCMessage base;
  char *source_id;
  char *type;
  int64_t timestamp;
  /*
   * true se ultrapassou limiar
   */
  protobuf_c_boolean alerta;
  Cidade__Leitura__ValorCase valor_case;
  union {
    float co2;
    float energia;
    float ruido;
    float temperatura;
    float umidade;
    /*
     * tráfego, pessoas
     */
    int32_t contagem;
  };
};
#define CIDADE__LEITURA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__leitura__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, CIDADE__LEITURA__VALOR__NOT_SET, {0} }


struct  Cidade__Comando
{
  ProtobufCMessage base;
  char *source_id;
  /*
   * "ativar", "desativar", "set_frequencia", "set_limiar"
   */
  char *acao;
  /*
   * usado quando acao = "set_frequencia" ou "set_limiar"
   */
  float valor;
};
#define CIDADE__COMANDO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__comando__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Cidade__RespostaComando
{
  ProtobufCMessage base;
  protobuf_c_boolean sucesso;
  char *mensagem;
};
#define CIDADE__RESPOSTA_COMANDO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__resposta_comando__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  Cidade__RequisicaoCliente
{
  ProtobufCMessage base;
  /*
   * "listar", "comando", "consulta"
   */
  char *tipo;
  /*
   * preenchido se tipo = "comando"
   */
  Cidade__Comando *comando;
  /*
   * ex: "media_temp_1h", "desvio_co2_24h"
   */
  char *consulta;
};
#define CIDADE__REQUISICAO_CLIENTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__requisicao_cliente__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, (char *)protobuf_c_empty_string }


struct  Cidade__RespostaGateway
{
  ProtobufCMessage base;
  /*
   * "fontes", "comando_ok", "consulta"
   */
  char *tipo;
  size_t n_fontes;
  Cidade__DiscoveryResponse **fontes;
  Cidade__RespostaComando *resultado_cmd;
  /*
   * JSON ou texto com resultado
   */
  char *dados_consulta;
};
#define CIDADE__RESPOSTA_GATEWAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cidade__resposta_gateway__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, NULL, (char *)protobuf_c_empty_string }


/* Cidade__DiscoveryRequest methods */
void   cidade__discovery_request__init
                     (Cidade__DiscoveryRequest         *message);
size_t cidade__discovery_request__get_packed_size
                     (const Cidade__DiscoveryRequest   *message);
size_t cidade__discovery_request__pack
                     (const Cidade__DiscoveryRequest   *message,
                      uint8_t             *out);
size_t cidade__discovery_request__pack_to_buffer
                     (const Cidade__DiscoveryRequest   *message,
                      ProtobufCBuffer     *buffer);
Cidade__DiscoveryRequest *
       cidade__discovery_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__discovery_request__free_unpacked
                     (Cidade__DiscoveryRequest *message,
                      ProtobufCAllocator *allocator);
/* Cidade__DiscoveryResponse methods */
void   cidade__discovery_response__init
                     (Cidade__DiscoveryResponse         *message);
size_t cidade__discovery_response__get_packed_size
                     (const Cidade__DiscoveryResponse   *message);
size_t cidade__discovery_response__pack
                     (const Cidade__DiscoveryResponse   *message,
                      uint8_t             *out);
size_t cidade__discovery_response__pack_to_buffer
                     (const Cidade__DiscoveryResponse   *message,
                      ProtobufCBuffer     *buffer);
Cidade__DiscoveryResponse *
       cidade__discovery_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__discovery_response__free_unpacked
                     (Cidade__DiscoveryResponse *message,
                      ProtobufCAllocator *allocator);
/* Cidade__Leitura methods */
void   cidade__leitura__init
                     (Cidade__Leitura         *message);
size_t cidade__leitura__get_packed_size
                     (const Cidade__Leitura   *message);
size_t cidade__leitura__pack
                     (const Cidade__Leitura   *message,
                      uint8_t             *out);
size_t cidade__leitura__pack_to_buffer
                     (const Cidade__Leitura   *message,
                      ProtobufCBuffer     *buffer);
Cidade__Leitura *
       cidade__leitura__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__leitura__free_unpacked
                     (Cidade__Leitura *message,
                      ProtobufCAllocator *allocator);
/* Cidade__Comando methods */
void   cidade__comando__init
                     (Cidade__Comando         *message);
size_t cidade__comando__get_packed_size
                     (const Cidade__Comando   *message);
size_t cidade__comando__pack
                     (const Cidade__Comando   *message,
                      uint8_t             *out);
size_t cidade__comando__pack_to_buffer
                     (const Cidade__Comando   *message,
                      ProtobufCBuffer     *buffer);
Cidade__Comando *
       cidade__comando__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__comando__free_unpacked
                     (Cidade__Comando *message,
                      ProtobufCAllocator *allocator);
/* Cidade__RespostaComando methods */
void   cidade__resposta_comando__init
                     (Cidade__RespostaComando         *message);
size_t cidade__resposta_comando__get_packed_size
                     (const Cidade__RespostaComando   *message);
size_t cidade__resposta_comando__pack
                     (const Cidade__RespostaComando   *message,
                      uint8_t             *out);
size_t cidade__resposta_comando__pack_to_buffer
                     (const Cidade__RespostaComando   *message,
                      ProtobufCBuffer     *buffer);
Cidade__RespostaComando *
       cidade__resposta_comando__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__resposta_comando__free_unpacked
                     (Cidade__RespostaComando *message,
                      ProtobufCAllocator *allocator);
/* Cidade__RequisicaoCliente methods */
void   cidade__requisicao_cliente__init
                     (Cidade__RequisicaoCliente         *message);
size_t cidade__requisicao_cliente__get_packed_size
                     (const Cidade__RequisicaoCliente   *message);
size_t cidade__requisicao_cliente__pack
                     (const Cidade__RequisicaoCliente   *message,
                      uint8_t             *out);
size_t cidade__requisicao_cliente__pack_to_buffer
                     (const Cidade__RequisicaoCliente   *message,
                      ProtobufCBuffer     *buffer);
Cidade__RequisicaoCliente *
       cidade__requisicao_cliente__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__requisicao_cliente__free_unpacked
                     (Cidade__RequisicaoCliente *message,
                      ProtobufCAllocator *allocator);
/* Cidade__RespostaGateway methods */
void   cidade__resposta_gateway__init
                     (Cidade__RespostaGateway         *message);
size_t cidade__resposta_gateway__get_packed_size
                     (const Cidade__RespostaGateway   *message);
size_t cidade__resposta_gateway__pack
                     (const Cidade__RespostaGateway   *message,
                      uint8_t             *out);
size_t cidade__resposta_gateway__pack_to_buffer
                     (const Cidade__RespostaGateway   *message,
                      ProtobufCBuffer     *buffer);
Cidade__RespostaGateway *
       cidade__resposta_gateway__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cidade__resposta_gateway__free_unpacked
                     (Cidade__RespostaGateway *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Cidade__DiscoveryRequest_Closure)
                 (const Cidade__DiscoveryRequest *message,
                  void *closure_data);
typedef void (*Cidade__DiscoveryResponse_Closure)
                 (const Cidade__DiscoveryResponse *message,
                  void *closure_data);
typedef void (*Cidade__Leitura_Closure)
                 (const Cidade__Leitura *message,
                  void *closure_data);
typedef void (*Cidade__Comando_Closure)
                 (const Cidade__Comando *message,
                  void *closure_data);
typedef void (*Cidade__RespostaComando_Closure)
                 (const Cidade__RespostaComando *message,
                  void *closure_data);
typedef void (*Cidade__RequisicaoCliente_Closure)
                 (const Cidade__RequisicaoCliente *message,
                  void *closure_data);
typedef void (*Cidade__RespostaGateway_Closure)
                 (const Cidade__RespostaGateway *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cidade__discovery_request__descriptor;
extern const ProtobufCMessageDescriptor cidade__discovery_response__descriptor;
extern const ProtobufCMessageDescriptor cidade__leitura__descriptor;
extern const ProtobufCMessageDescriptor cidade__comando__descriptor;
extern const ProtobufCMessageDescriptor cidade__resposta_comando__descriptor;
extern const ProtobufCMessageDescriptor cidade__requisicao_cliente__descriptor;
extern const ProtobufCMessageDescriptor cidade__resposta_gateway__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cidade_2eproto__INCLUDED */
